/*
 * This file is generated by jOOQ.
 */
package com.demo.demo1.model.jooq;


import com.demo.demo1.model.jooq.tables.Author;
import com.demo.demo1.model.jooq.tables.AuthorBook;
import com.demo.demo1.model.jooq.tables.Book;
import com.demo.demo1.model.jooq.tables.FlywaySchemaHistory;
import com.demo.demo1.model.jooq.tables.records.AuthorBookRecord;
import com.demo.demo1.model.jooq.tables.records.AuthorRecord;
import com.demo.demo1.model.jooq.tables.records.BookRecord;
import com.demo.demo1.model.jooq.tables.records.FlywaySchemaHistoryRecord;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AuthorRecord> AUTHOR_PKEY = UniqueKeys0.AUTHOR_PKEY;
    public static final UniqueKey<AuthorBookRecord> AUTHOR_BOOK_PKEY = UniqueKeys0.AUTHOR_BOOK_PKEY;
    public static final UniqueKey<BookRecord> BOOK_PKEY = UniqueKeys0.BOOK_PKEY;
    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = UniqueKeys0.FLYWAY_SCHEMA_HISTORY_PK;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AuthorBookRecord, AuthorRecord> AUTHOR_BOOK__AUTHOR_BOOK_AUTHOR_ID_FKEY = ForeignKeys0.AUTHOR_BOOK__AUTHOR_BOOK_AUTHOR_ID_FKEY;
    public static final ForeignKey<AuthorBookRecord, BookRecord> AUTHOR_BOOK__AUTHOR_BOOK_BOOK_ID_FKEY = ForeignKeys0.AUTHOR_BOOK__AUTHOR_BOOK_BOOK_ID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<AuthorRecord> AUTHOR_PKEY = Internal.createUniqueKey(Author.AUTHOR, "author_pkey", Author.AUTHOR.ID);
        public static final UniqueKey<AuthorBookRecord> AUTHOR_BOOK_PKEY = Internal.createUniqueKey(AuthorBook.AUTHOR_BOOK, "author_book_pkey", AuthorBook.AUTHOR_BOOK.AUTHOR_ID, AuthorBook.AUTHOR_BOOK.BOOK_ID);
        public static final UniqueKey<BookRecord> BOOK_PKEY = Internal.createUniqueKey(Book.BOOK, "book_pkey", Book.BOOK.ID);
        public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, "flyway_schema_history_pk", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<AuthorBookRecord, AuthorRecord> AUTHOR_BOOK__AUTHOR_BOOK_AUTHOR_ID_FKEY = Internal.createForeignKey(com.demo.demo1.model.jooq.Keys.AUTHOR_PKEY, AuthorBook.AUTHOR_BOOK, "author_book__author_book_author_id_fkey", AuthorBook.AUTHOR_BOOK.AUTHOR_ID);
        public static final ForeignKey<AuthorBookRecord, BookRecord> AUTHOR_BOOK__AUTHOR_BOOK_BOOK_ID_FKEY = Internal.createForeignKey(com.demo.demo1.model.jooq.Keys.BOOK_PKEY, AuthorBook.AUTHOR_BOOK, "author_book__author_book_book_id_fkey", AuthorBook.AUTHOR_BOOK.BOOK_ID);
    }
}
