/*
 * This file is generated by jOOQ.
 */
package com.demo.demo1.model.jooq;


import com.demo.demo1.model.jooq.tables.Author;
import com.demo.demo1.model.jooq.tables.AuthorBook;
import com.demo.demo1.model.jooq.tables.Book;
import com.demo.demo1.model.jooq.tables.FlywaySchemaHistory;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 832091139;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.author</code>.
     */
    public final Author AUTHOR = com.demo.demo1.model.jooq.tables.Author.AUTHOR;

    /**
     * The table <code>public.author_book</code>.
     */
    public final AuthorBook AUTHOR_BOOK = com.demo.demo1.model.jooq.tables.AuthorBook.AUTHOR_BOOK;

    /**
     * The table <code>public.book</code>.
     */
    public final Book BOOK = com.demo.demo1.model.jooq.tables.Book.BOOK;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.demo.demo1.model.jooq.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Author.AUTHOR,
            AuthorBook.AUTHOR_BOOK,
            Book.BOOK,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY);
    }
}
